### PR TITLE
Fix logic for getting source files in the main chunk

### LINKED ISSUE #295: Chunk-id-loader is broken with the webpack 4 upgrade
```
error: (server) ./node_modules/fusion-cli/build/chunk-id-loader.js!./src/components/root.js
Module build failed: Error: no result from manifest for /Users/giancarloanemone/dev/uber/scaffold/src/components/root.js
    at _generateSource (/Users/giancarloanemone/dev/uber/scaffold/node_modules/fusion-cli/build/chunk-id-loader.js:28:24)
```

### PR DESCRIPTION
**Pull request by ganemone**
Fixes #295

### CODE REVIEW

**Comment by ganemone** [comment]
!merge

File: build/chunk-module-manifest-plugin.js [hunk 1]
```diff
@@ -22,7 +22,17 @@ class ChunkModuleManifestPlugin {
           const chunkIdsByFile = new Map();
           chunks.forEach(c => {
             const chunkId = c.id;
-            const files = Array.from(c.modulesIterable, m => m.resource);
+            const files = Array.from(c.modulesIterable, m => {
+              if (m.resource) {
+                return m.resource;
+              }
+              if (m.modules) {
+                return m.modules.map(module => module.resource);
```
Comment (KevinGrandon) [inline build/chunk-module-manifest-plugin.js]: That's a better fix, thanks!
