### PR TITLE
Ensure `test --watch` continues watching after test failure

### LINKED ISSUE #51: fusion test --watch exits when tests fail
This should behave the same way that `dev` does. On test failure, we should wait for a recompilation and then re-run tests.

### PR DESCRIPTION
**Pull request by lhorie**
Resolves #51

### CODE REVIEW

File: commands/test.js [hunk 1]
```diff
@@ -64,7 +64,9 @@ exports.run = async function({dir = '.', cover, watch, skipBuild}) {
   await runTests();
 
   if (watch) {
-    compiler.on('done', runTests);
+    compiler.on('done', () => {
+      runTests().catch(() => {}); // ignore error, since test output is already actionable enough
```
Comment (davidkearns) [inline commands/test.js]: Should we log something here?

Comment (lhorie) [reply commands/test.js]: I think logging would make the test output unnecessarily noisy. The stack trace is already part of the test report

**Comment by lhorie** [comment]
!merge
